export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="zs"
DISABLE_AUTO_UPDATE="true"
HIST_STAMPS="yyyy-mm-dd"

plugins=(git autojump rsync docker go cp tmux)
source $ZSH/oh-my-zsh.sh

[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

setopt noincappendhistory
setopt nosharehistory
set -o shwordsplit
source $HOME/.bash_profile

